// Test generated by RoostGPT for test go-email using AI Type Open AI and AI Model gpt-4

package main

import "testing"

func TestAdd_28d8c9c450(t *testing.T) {
	t.Run("positive numbers", func(t *testing.T) {
		result := Add_28d8c9c450(2, 3)
		if result != 5 {
			t.Errorf("Expected 5, but got %d", result)
		}
	})

	t.Run("negative numbers", func(t *testing.T) {
		result := Add_28d8c9c450(-2, -3)
		if result != -5 {
			t.Errorf("Expected -5, but got %d", result)
		}
	})

	t.Run("zero", func(t *testing.T) {
		result := Add_28d8c9c450(0, 0)
		if result != 0 {
			t.Errorf("Expected 0, but got %d", result)
		}
	})

	t.Run("positive and negative", func(t *testing.T) {
		result := Add_28d8c9c450(2, -3)
		if result != -1 {
			t.Errorf("Expected -1, but got %d", result)
		}
	})
}

func Add_28d8c9c450(a, b int) int {
	return a + b
}
